import type { Track } from './types';

export const Tracks: Track[] = [
  {
    id: "1",
    title: "24",
    artist: "Xcho",
    cover: "./assets/cover-songs/24-cover.png",
    url: "https://files.catbox.moe/5ik74q.mp3",
    favorite: false,
  },
  {
    id: "2",
    title: "Ak 47",
    artist: "Pablo",
    cover: "./assets/cover-songs/ak-47-cover.png",
    url: "https://files.catbox.moe/wsfll1.mp3",
    favorite: false,
  },
  {
    id: "3",
    title: "Баллада",
    artist: "Xcho",
    cover: "./assets/cover-songs/balado-cover.png",
    url: "https://files.catbox.moe/3yzbfo.mp3",
    favorite: false,
  },
  {
    id: "4",
    title: "Есенин",
    artist: "Jawwa",
    cover: "./assets/cover-songs/esenin-cover.png",
    url: "https://files.catbox.moe/n6wtcc.mp3",
    favorite: false,
  },
  {
    id: "5",
    title: "Jet",
    artist: "Macan",
    cover: "./assets/cover-songs/jet-cover.png",
    url: "https://files.catbox.moe/zz0n98.mp3",
    favorite: false,
  },
  {
    id: "6",
    title: "Как же",
    artist: "Macan",
    cover: "./assets/cover-songs/kak-je-cover.png",
    url: "https://files.catbox.moe/ggjwdz.mp3",
    favorite: false,
  },
  {
    id: "7",
    title: "Life Letters",
    artist: "Never Get Used To People",
    cover: "./assets/cover-songs/life-letters-cover.png",
    url: "https://files.catbox.moe/szypyp.mp3",
    favorite: false,
  },
  {
    id: "8",
    title: "Матушка Земля",
    artist: "Phonk",
    cover: "./assets/cover-songs/matushka-cover.png",
    url: "https://files.catbox.moe/0oohvk.mp3",
    favorite: false,
  },
  {
    id: "9",
    title: "Мерин",
    artist: "Xcho",
    cover: "./assets/cover-songs/merin-cover.png",
    url: "https://files.catbox.moe/dnphi0.mp3",
    favorite: false,
  },
  {
    id: "10",
    title: "Мир на двоих",
    artist: "Xcho",
    cover: "./assets/cover-songs/mir-na-dvoix-xcho.png",
    url: "https://files.catbox.moe/w7uqr2.mp3",
    favorite: false,
  },
  {
    id: "11",
    title: "Нежно",
    artist: "Izotov",
    cover: "./assets/cover-songs/unknown-cover.png",
    url: "https://files.catbox.moe/arl99h.mp3",
    favorite: false,
  },
  {
    id: "12",
    title: "Only You",
    artist: "Xcho",
    cover: "./assets/cover-songs/only-you-cover.png",
    url: "https://files.catbox.moe/se8gh4.mp3",
    favorite: false,
  },
  {
    id: "13",
    title: "Ты и Я",
    artist: "Xcho",
    cover: "./assets/cover-songs/ti-i-ya-cover.png",
    url: "https://files.catbox.moe/jixo2n.mp3",
    favorite: false,
  },
  {
    id: "14",
    title: "Тримай x Нежно",
    artist: "7azilov",
    cover: "./assets/cover-songs/trimay-cover.png",
    url: "https://files.catbox.moe/bigdhc.mp3",
    favorite: false,
  },
  {
    id: "15",
    title: "Уйду",
    artist: "Xcho",
    cover: "./assets/cover-songs/uydu-cover.png",
    url: "https://files.catbox.moe/xht8zf.mp3",
    favorite: false,
  },
  {
    id: "16",
    title: "Вороны",
    artist: "Xcho",
    cover: "./assets/cover-songs/voroni-cover.png",
    url: "https://files.catbox.moe/1hjhck.mp3",
    favorite: false,
  },
  {
    id: "17",
    title: "Зачерованя",
    artist: "Xcho",
    cover: "./assets/cover-songs/zcherovanya-cover.png",
    url: "https://files.catbox.moe/lkj920.mp3",
    favorite: false,
  },
  {
    id: "18",
    title: "Studytonight",
    artist: "Youtube",
    cover: "./assets/cover-songs/unknown-cover.png",
    url: "https://files.catbox.moe/nt6etu.mp3",
    favorite: false,
  },
  {
    id: "19",
    title: "Phonk",
    artist: "Spotify",
    cover: "./assets/cover-songs/phonk-cover.png",
    url: "https://files.catbox.moe/gu9pjy.mp3",
    favorite: false,
  },
];