import type { Track } from './types';

export const Tracks: Track[] = [
  {
    id: "1",
    title: "24",
    artist: "Xcho",
    cover: "./src/assets/cover-songs/24-cover.png",
    url: "./src/assets/songs/24-xcho.mp3",
    favorite: false,
  },
  {
    id: "2",
    title: "Ak 47",
    artist: "Pablo",
    cover: "./src/assets/cover-songs/ak-47-cover.png",
    url: "./src/assets/songs/ak-47-pablo.mp3",
    favorite: false,
  },
  {
    id: "3",
    title: "Баллада",
    artist: "Xcho",
    cover: "./src/assets/cover-songs/balado-cover.png",
    url: "./src/assets/songs/ballada-xcho.mp3",
    favorite: false,
  },
  {
    id: "4",
    title: "Есенин",
    artist: "Jawwa",
    cover: "./src/assets/cover-songs/esenin-cover.png",
    url: "./src/assets/songs/esenin-jawwa.mp3",
    favorite: false,
  },
  {
    id: "5",
    title: "Jet",
    artist: "Macan",
    cover: "./src/assets/cover-songs/jet-cover.png",
    url: "./src/assets/songs/jet-macan.mp3",
    favorite: false,
  },
  {
    id: "6",
    title: "Как же",
    artist: "Macan",
    cover: "./src/assets/cover-songs/kak-je-cover.png",
    url: "./src/assets/songs/kak-je-macan.mp3",
    favorite: false,
  },
  {
    id: "7",
    title: "Life Letters",
    artist: "Never Get Used To People",
    cover: "./src/assets/cover-songs/life-letters-cover.png",
    url: "./src/assets/songs/life-letters-never-get-used-to-people.mp3",
    favorite: false,
  },
  {
    id: "8",
    title: "Матушка Земля",
    artist: "Phonk",
    cover: "./src/assets/cover-songs/matushka-cover.png",
    url: "./src/assets/songs/matushka-phonk.mp3",
    favorite: false,
  },
  {
    id: "9",
    title: "Мерин",
    artist: "Xcho",
    cover: "./src/assets/cover-songs/merin-cover.png",
    url: "./src/assets/songs/merin-xcho.mp3",
    favorite: false,
  },
  {
    id: "10",
    title: "Мир на двоих",
    artist: "Xcho",
    cover: "./src/assets/cover-songs/mir-na-dvoix-xcho.png",
    url: "./src/assets/songs/mir-na-dvoix-xcho.mp3",
    favorite: false,
  },
  {
    id: "11",
    title: "Нежно",
    artist: "Izotov",
    cover: "./src/assets/cover-songs/trimay-cover.png",
    url: "./src/assets/songs/nejno-izotov.mp3",
    favorite: false,
  },
  {
    id: "12",
    title: "Only You",
    artist: "Xcho",
    cover: "./src/assets/cover-songs/only-you-cover.png",
    url: "./src/assets/songs/only-yoy-xcho.mp3",
    favorite: false,
  },
  {
    id: "13",
    title: "Ты и Я",
    artist: "Xcho",
    cover: "./src/assets/cover-songs/ti-i-ya-cover.png",
    url: "./src/assets/songs/ti-i-ya-xcho.mp3",
    favorite: false,
  },
  {
    id: "14",
    title: "Тримай x Нежно",
    artist: "7azilov",
    cover: "./src/assets/cover-songs/trimay-cover.png",
    url: "./src/assets/songs/trimay-nejno-7azilov.mp3",
    favorite: false,
  },
  {
    id: "15",
    title: "Уйду",
    artist: "Xcho",
    cover: "./src/assets/cover-songs/uydu-cover.png",
    url: "./src/assets/songs/uydu-xcho.mp3",
    favorite: false,
  },
  {
    id: "16",
    title: "Вороны",
    artist: "Xcho",
    cover: "./src/assets/cover-songs/voroni-cover.png",
    url: "./src/assets/songs/voroni-xcho.mp3",
    favorite: false,
  },
  {
    id: "17",
    title: "Зачерованя",
    artist: "Xcho",
    cover: "./src/assets/cover-songs/zcherovanya-cover.png",
    url: "./src/assets/songs/zacherovanya-xcho.mp3",
    favorite: false,
  },
];